Poc.Web/Controllers/LoginController.cs
using System;
using System.Security.Authentication;
using System.Web.Mvc;
using System.Web.Security;
using Poc.Core.Entities.AdminModule;
using Poc.Core.Validation;
using Poc.Web.Models.ViewModels;
using Poc.Service.Membership;
using Poc.Web.Mvc.Controllers;

namespace Poc.Web.Controllers
{
	public class LoginController : BaseController
	{
		private readonly IAuthenticationService _authenticationService;

		/// <summary>
		/// Create and initialize an instance of the LoginController class.
		/// </summary>
		/// <param name="authenticationService"></param>
		/// <param name="modelValidator"></param>
		public LoginController(IAuthenticationService authenticationService, IModelValidator<LoginViewData> modelValidator)
		{
			this._authenticationService = authenticationService;
			this.ModelValidator = modelValidator;
		}

		public ActionResult Index(string returnUrl)
		{
			ViewData["ReturnUrl"] = returnUrl;
			return View(new LoginViewData());
		}

		[AcceptVerbs("POST")]
		public ActionResult Login(string returnUrl)
		{
			var loginUser = new LoginViewData();
			try
			{
				if (TryUpdateModel(loginUser) && ValidateModel(loginUser))
				{
					AppUser user = _authenticationService.AuthenticateUser(loginUser.Username, loginUser.Password, Request.UserHostAddress);

					FormsAuthentication.SetAuthCookie(user.AppUserId.ToString(), false);
					if (!String.IsNullOrEmpty(returnUrl))
					{
						return Redirect(returnUrl);
					}
					return RedirectToAction("Index", "Dashboard");
				}
			}
			catch (AuthenticationException ex)
			{
				Logger.WarnFormat("User {0} unsuccessfully logged in with password {1}.", loginUser.Username, loginUser.Password);
				Messages.AddException(ex);
			}
			catch (Exception ex)
			{
				Logger.Error("Unexpected error while logging in", ex);
				Messages.AddException(ex);
			}
			return View("Index", loginUser);
		}

		public ActionResult Logout()
		{
			FormsAuthentication.SignOut();
			return RedirectToAction("Index");
		}
	}
}

Poc.Web/Controllers/NodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Poc.Core.Entities.AdminModule;
using Poc.Core.Validation;
using Poc.Service.AdminModule;

namespace Poc.Web.Controllers
{
    public class NodesController : ManagerController
    {
        private readonly INodeService _nodeService;
        private readonly IUserService _userService;
        public NodesController(INodeService nodeService,IUserService userService, IModelValidator<Node> modelValidator)
		{
			_nodeService = nodeService;
            _userService = userService;
			ModelValidator = modelValidator;
		}
        //
        // GET: /Nodes/

        public ActionResult Index()
        {
            ViewData["Roles"] = _userService.GetAllRoles();
            var nodes = _nodeService.GetAllNodes();
            return View("Index",nodes);
        }

       
        //
        // GET: /Nodes/Create

        public ActionResult Create()
        {
            ViewData["Roles"] = _userService.GetAllRoles();
            var node = new Node();
            return View("Create", node);
        }

        //
        // POST: /Nodes/Create

        [HttpPost]
        public ActionResult Create(int[] roleIds)
        {
            var newNode = new Node();
            var roles = _userService.GetAllRoles();
            //try
            //{
                UpdateModel(newNode, new[] {"Name", "Description", "ControllerName", "ActionName", "ShowInNavigation"});
                //_nodeService.SetNodePermissions(newNode,RoleIds);
                if (ValidateModel(newNode))
                {
                    _nodeService.SaveNode(newNode,roleIds);
                    Messages.AddFlashMessageWithParams("NodeCreatedMessage", newNode.Name);
                    return RedirectToAction("Index");
                }
            //}
            //catch (Exception ex)
            //{
            //    Messages.AddException(ex);
            //}

            ViewData["Roles"] = roles;

            return View("Create", newNode);
        }

        //
        // GET: /Nodes/Edit/5

        public ActionResult Edit(int id)
        {
            ViewData["Roles"] = _userService.GetAllRoles();
            var node = _nodeService.GetNodeById(id);
            return View("Edit",node);
        }

        //
        // POST: /Nodes/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, int[] roleIds)
        {
            var node = _nodeService.GetNodeById(id);
            var roles = _userService.GetAllRoles();
            try
            {
                UpdateModel(node, new[] { "Name", "Description", "ControllerName", "ActionName", "ShowInNavigation" });
                
                if (ValidateModel(node))
                {
                    _nodeService.UpdateNode(node,roleIds);
                    Messages.AddFlashMessageWithParams("NodeCreatedMessage", node.Name);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Messages.AddException(ex);
            }

            ViewData["Roles"] = roles;

            return View("Edit", node);
        }

        //
        // POST: /Nodes/Delete/5

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var node = _nodeService.GetNodeById(id);
            try
            {
                _nodeService.DeleteNode(node);
                Messages.AddFlashMessageWithParams("NodeDeletedMessage", node.Name);
            }
            catch(Exception ex)
            {
                Messages.AddFlashException(ex);
            }
            return RedirectToAction("Index");
        }


        public ActionResult PermissionsImport()
        {
            var controllerTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a => a.GetTypes())
                .Where(t => t != null
                    && t.IsPublic
                    && t.Name.EndsWith("Controller", StringComparison.OrdinalIgnoreCase)
                    && !t.IsAbstract
                    && typeof(IController).IsAssignableFrom(t));

            var controllerMethods = controllerTypes.ToDictionary(controllerType => controllerType,
                    controllerType => controllerType.GetMethods(BindingFlags.Public | BindingFlags.Instance)
                    .Where(m => typeof(ActionResult).IsAssignableFrom(m.ReturnType)));

            foreach (var controller in controllerMethods)
            {
                string controllerName = controller.Key.Name;
                foreach (var controllerAction in controller.Value)
                {
                    string controllerActionName = controllerAction.Name;
                    if (controllerName.EndsWith("Controller"))
                    {
                        controllerName = controllerName.Substring(0, controllerName.LastIndexOf("Controller"));
                    }

                    string permissionDescription = string.Format("{0}-{1}", controllerName, controllerActionName);
                    Node node = _nodeService.GetNode(controllerName, controllerActionName);
                    
                    if (node == null)
                    {
                        if (ModelState.IsValid)
                        {
                            var newNode = new Node()
                            {
                                Name = permissionDescription,
                                ControllerName = controllerName,
                                ActionName =controllerActionName,
                                ShowInNavigation = true
                            };
                            _nodeService.SaveNode(newNode, null);
                        }
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Poc.Web/Controllers/TabsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Poc.Core.Entities.AdminModule;
using Poc.Core.Enumerations;
using Poc.Core.Validation;
using Poc.Service.AdminModule;

namespace Poc.Web.Controllers
{
    public class TabsController : ManagerController
    {
        private readonly ITabService _tabService;
        private readonly IUserService _userService;
        private readonly INodeService _nodeService;
        public TabsController(ITabService tabService, IUserService userService, INodeService nodeService, IModelValidator<Tab> modelValidator)
        {
            _tabService = tabService;
            _userService = userService;
            _nodeService = nodeService;
            ModelValidator = modelValidator;
        }
        public ActionResult Index()
        {
            return View();
        }
        
        //
        // GET: /Tabs/Create

        public ActionResult Create()
        {
            ViewData["Roles"] = _userService.GetAllRoles();
            var newTab = new Tab();
            return View("Create",newTab);
        }

        //
        // POST: /Tabs/Create

        [HttpPost]
        public ActionResult Create(int[] roleIds)
        {
            var newTab = new Tab();
          
            try
            {
                if (TryUpdateModel(newTab, new[] {"TabName", "ControllerName"}))
                {
                    if (ValidateModel(newTab))
                    {
                        _tabService.CreateTab(newTab, roleIds);
                        Messages.AddFlashMessageWithParams("PageCreatedMessage", newTab.TabName);

                        return RedirectToAction("Edit", new {id = newTab.TabId});
                    }
                }
            }
            catch (Exception ex)
            {
                Messages.AddException(ex);
            }

            ViewData["Roles"] = _userService.GetAllRoles();
            return View("Create", newTab);
        }

        //
        // GET: /Tabs/Edit/5

        public ActionResult Edit(int id)
        {
            ViewData["Roles"] = _userService.GetAllRoles();
            var tab = _tabService.GetTabById(id);
            return View("Edit",tab);
        }

        //
        // POST: /Tabs/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, int[] roleIds)
        {
            var tab = _tabService.GetTabById(id);
            
            try
            {
                if (TryUpdateModel(tab, new[] {"TabName", "ControllerName"}))
                {
                    if (ValidateModel(tab))
                    {
                        _tabService.UpdateTab(tab, roleIds);
                        Messages.AddFlashMessage("PagePropertiesUpdatedMessage");
                    }
                }
            }
            catch (Exception ex)
            {
                Messages.AddException(ex);
            }
            ViewData["Roles"] = _userService.GetAllRoles();
            return View("Edit", _tabService.GetTabById(id));
        }

        //
        // GET: /Tabs/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Tabs/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult MoveNode(int id, int nodeid, string direction)
        {
            try
            {
                var direc = (NodePositionMovement) Enum.Parse(typeof (NodePositionMovement), direction, true);
                _tabService.MovePage(id, nodeid, direc);
                Messages.AddFlashMessage("PageMovedMessage");
            }
            catch (Exception ex)
            {
                Messages.AddException(ex);
            }
            ViewData["Roles"] = _userService.GetAllRoles();
            var tab = _tabService.GetTabById(id);
            return View("Edit", tab);
        }

        public ActionResult DeleteTabNode(int id, int nodeid)
        {   
             try
             {
                 _tabService.DeletePage(id, nodeid);
                Messages.AddFlashMessage("NodeDeletedMessage");
            }
            catch (Exception ex)
            {
                Messages.AddException(ex);
            }

            ViewData["Roles"] = _userService.GetAllRoles();
            var tab = _tabService.GetTabById(id);
            return View("Edit", tab);
        }

        public ActionResult SelectTabNode(int id)
        {
            var tab = _tabService.GetTabById(id);
            var nodes = _nodeService.GetAllNodes();
            IList<Node> filiterd = nodes.Where(node => !tab.GetAllNodeIds().Contains(node.NodeId)).ToList();
            ViewData["tabId"] = tab.TabId;

            return View("_SelectNode", filiterd);
        }

        [HttpPost]
        public ActionResult SelectTabNode(int id,int[] nodeIds)
        {
            if (nodeIds != null && nodeIds.Length > 0)
            {
                try
                {
                    var pages = new List<Page>();
                    int len = nodeIds.Length;
                    int pos = _tabService.GetPageCount(id);
                    for (int i = 0; i < len; i++)
                    {
                        var tabNode = new Page
                        {
                            IsActive = true,
                            MenuType = NodeMenuTypeEnum.LeftSide.ToString(),
                            NodeId =  nodeIds[i],
                            TabId = id,
                            Position = pos
                        };
                        pos++;
                        pages.Add(tabNode);
                    }

                    _tabService.UpdateTab(id,pages);
                    Messages.AddFlashMessage("PagePropertiesUpdatedMessage");
                }
                catch (Exception ex)
                {
                    Messages.AddException(ex);
                }
            }

            var tab = _tabService.GetTabById(id); 
            ViewData["Roles"] = _userService.GetAllRoles();
            return View("Edit", tab);
        }
    }
}

Poc.Web/Views/Shared/MainMenu.cshtml
@model  MenuViewData 
<div id="mainmenu">
	@if (Model.StandardMainMenuItems.Count > 0) { 
	<div id="mainmenu-standard">
		<ul>
		@foreach(var menuItem in Model.StandardMainMenuItems) {  
			Html.RenderPartial("_MenuItem", menuItem); 
		} 
		</ul>
	</div>
	} 
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('.expander').click(function(e) {
			e.stopPropagation();
			$(this).next('ul').slideToggle(100);
		});

		$(document).click(function() {
			$('.expander').next('ul:visible').slideToggle(100);
		});
	});
</script>

Poc.Web/Views/Shared/Messages.cshtml
@model Poc.Web.Mvc.ViewModels.MessageViewData 
<div id="messagewrapper" style="display:none">
	@{
	    var messages = Model.GetDisplayMessages();
	    foreach (string messageType in MessageType.GetTypes())
	    {
	        if (messages[messageType].Count > 0)
	        {
	            <div class="@messageType.ToLower()box">
	                <img src="@Url.Content("~/Content/Images/cross.gif")" class="close_message" style="float: right;  cursor: pointer" alt="Close" />
	                @foreach (string message in messages[messageType])
	                {
	                    @MvcHtmlString.Create(message)
                              <br />
	                } 
	            </div>
	        }
	    }
	} 
</div>
<script type="text/javascript">
	$(document).ready(function() {
		// Display messages on page load if the #messagewrapper has content
		if ($("#messagewrapper").children().length > 0) {
			displayMessages();
		}
	});	
</script>

Poc.Web/Views/Shared/PartialMessages.cshtml
@model Poc.Web.Mvc.ViewModels.MessageViewData 
<div class="partialmessagewrapper">
    @{
        var messages = ViewData.Model.GetDisplayMessages();
        foreach (string messageType in MessageType.GetTypes())
         {
             if (messages[messageType].Count > 0)
             {
                 <div class="@messageType.ToLower() box">
                     <img src="@Url.Content("~/Content/Images/cross.gif")" class="close_message" style="float: right; cursor: pointer" alt="Close" />
                     @foreach (string message in messages[messageType])
                     {
                         @MvcHtmlString.Create(message) <br />
                     } 
                 </div>
             }
         }
    } 
</div>

Poc.Web/Views/Shared/ViewAndEditRolesSelector.cshtml
@using System.Collections
@model IEnumerable<Role>

@GlobalResources.ViewRolesLabel 
@if (ViewData.ContainsKey("AllRoles")) { 
	<ul>
	@foreach (Role role in (IEnumerable)ViewData["AllRoles"]) { 
		<li>
			<input type="checkbox" name="ViewRoleIds" id="viewrole_@role.Id " value="@ViewData.Model.Any(p => p.RoleId == role.RoleId) ? 'checked' : @String.Empty"  />
			<label for="viewrole_@role.Id ">@role.Name </label>
		</li>
	} 
	</ul>
} 

Poc.Web/Views/Shared/_AdminNavigation.cshtml
<br/>
<h3 class="tabarea">Tabs</h3>
<div class="taskcontainer">
        @if (ViewData.ContainsKey("PocTabs"))
        {
            <div class="taskareatab">
                <ul>
                    @foreach (Tab tab in (List<Tab>)ViewData["PocTabs"])
                    {
                        <li>
                            @Html.ActionLink(tab.TabName, "Edit", "Tabs", new { id = tab.TabId }, null)
                        </li>
                    }
                </ul>
            </div>
        }
        @Html.ActionLink("Add a new tab", "Create", "Tabs")
    
</div>

<br />
<h3 class="nodearea">Nodes</h3>
<div class="taskcontainer">
    <br/>
    <ul>
        <li>
            @Html.ActionLink("Manage Nodes", "Index", "Nodes")
        </li>
    </ul>
</div>
<br/>
<h3 class="rolearea">Roles</h3>
<div class="taskcontainer">
    <br/>
    <ul>
            <li>
                @Html.ActionLink("Manage Roles", "Roles", "Users")
            </li>
        </ul>
</div>
<br/>
<h3 class="userarea">Users</h3>
<div class="taskcontainer">
    <br/>
    <ul>
            <li>
                @Html.ActionLink("Manage Users", "Index", "Users")
            </li>
        </ul>
</div>

Poc.Web/Views/Shared/_Header.cshtml
<div id="header">
	<img height="60" width="172" alt="Poc logo" src="@Url.Content("~/Content/Images/Poc-logo.png")"/>
	@if (ViewData.ContainsKey("PocUser"))
	{
	    <div id="userinfo">
	        @GlobalResources.LoggedInAsLabel  @MvcHtmlString.Create(((AppUser)(ViewData["PocUser"])).FullName) 
             <br/>
	        @Html.ActionLink(GlobalResources.LogoutButtonLabel, "Logout", "Login") 
	    </div>
	}
	<p>@GlobalResources.PocSiteManagerLabel </p>
</div>

Poc.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>@ViewBag.Title :: PocLAB Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/addis/css")
        @Styles.Render("~/Content/addis/jquery/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript">
            PocConfig.ContentDir = @Url.Content("~/Content/");
            PocConfig.ConfirmText = '@GlobalResources.AreYouSure';
        </script>
    </head>
    <body>
        @{
            Html.RenderPartial("_Header");
            Html.RenderPartial("MainMenu", ViewData["MenuViewData"]);
            Html.RenderPartial("Messages", ViewData["Messages"]);
        }
        <div id="contentcontainer">
            <div id="subcontentarea">
                <div id="taskarea">
                    @RenderSection("cphTasks", required: false)
                </div>
            </div>
            <div id="contentarea">
                @RenderBody()
            </div>
        </div>

    </body>
</html>

Poc.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>PocLAB Manager :: @ViewBag.Title </title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <script type="text/javascript">
            Url = function () { }
            Url.prototype= {
                _relativeRoot: '@VirtualPathUtility.ToAbsolute("~/")',
                resolve: function(relative) {
                    var resolved = relative;
                    if (relative.charAt(0) == '~')
                        resolved = this._relativeRoot + relative.substring(2);
                    return resolved;
                }
            }
            $Url = new Url();
        </script>
       
         <link rel="stylesheet" href="~/Content/addis/Manager.css" type="text/css">
        <link rel="stylesheet" href="~/Content/addis/jquery-ui/smoothness/jquery-ui-1.7.2.poc.css" type="text/css">
        <script type="text/javascript" src="~/Scripts/jquery-1.8.2.min.js"></script>
        <script type="text/javascript" src="~/Scripts/jquery.form.js"></script>
        <script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
        <script type="text/javascript" src="~/Scripts/poc.common.js"></script>
        <script type="text/javascript" src="~/Scripts/jquery-ui-1.8.24.min.js"></script>

        @*@Styles.Render("~/Content/addis/css")
        @Styles.Render("~/Content/addis/jquery/css")
        
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript" src="~/Scripts/jquery.form.js"></script>*@
       @RenderSection("headsection", required: false)
    </head>
    <body>
        @{
            Html.RenderPartial("_Header");
            Html.RenderPartial("MainMenu", ViewData["MenuViewData"]);
            Html.RenderPartial("Messages", ViewData["Messages"]);
        }
        <div id="contentcontainer">
            <div id="subcontentarea">
                <div id="taskarea">
                    @RenderSection("cphTasks", required: false)
                    @{ Html.RenderPartial("_AdminNavigation"); }
                </div>
               
            </div>
            <div id="contentarea">
                @RenderBody()
            </div>
        </div>
        @RenderSection("scripts", required: false)
    </body>
</html>

Poc.Web/Views/Shared/_LayoutDefault.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/addis/css")
    @Styles.Render("~/Content/addis/jquery/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
    @{
        Html.RenderPartial("_Header");
        Html.RenderPartial("Messages", ViewData["Messages"]);
    }
    <div>
        @RenderBody()
    </div>
    
    @RenderSection("scripts", required: false)
</body>
</html>

Poc.Web/Views/Shared/_LayoutModule.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title :: PocLAB Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/addis/css")
    @Styles.Render("~/Content/addis/jquery/css")
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    <script type="text/javascript" src="~/Scripts/jquery.form.js" ></script>
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        PocConfig.ContentDir = @Url.Content("~/Content/");
        PocConfig.ConfirmText = '@GlobalResources.AreYouSure';
    </script>
</head>
<body>
    @{
        Html.RenderPartial("_Header");
        Html.RenderPartial("MainMenu", ViewData["MenuViewData"]);
        Html.RenderPartial("Messages", ViewData["Messages"]);
    }
    <div id="contentcontainer">
        <div id="subcontentarea">
            <div id="taskarea">
                @{ Html.RenderPartial("_ModuleNavigation"); }
            </div>
        </div>
        <div id="contentarea">
            @RenderBody()
        </div>
    </div>

</body>

</html>

Poc.Web/Views/Shared/_MenuItem.cshtml
@model Poc.Web.Models.ViewModels.MenuItemData
            
<li @Html.Raw(@Model.IsSelected ? "class=\"selected\"" : @String.Empty)>
    <a href="@Model.Url">
        @if (! String.IsNullOrEmpty(Model.IconUrl)) { 
            <img src="@Model.IconUrl" alt="" />
        } 
        @ViewData.Model.Text </a>
    
	@if (Model.PopUpMenuItems.Count > 0)
	{
	    <div class="expander"><img src="@Url.Content("~/Content/Images/bullet_arrow_down.png")" alt="expand" /></div>
	    <ul>
	        @foreach (var subMenuItem in Model.PopUpMenuItems)
	        {
	            <li @Html.Raw(@subMenuItem.IsSelected ? "class=\"selected\"" : @String.Empty)>
	                 <a href="@subMenuItem.Url">
	                           @if (! String.IsNullOrEmpty(subMenuItem.IconUrl))
	                           {
	                               <img src="@subMenuItem.IconUrl" alt="" />
	                           }
	                           @subMenuItem.Text </a>
	            </li>
	        } 
	    </ul>
	}
</li>

Poc.Web/Views/Shared/_ModuleNavigation.cshtml
@model MenuItemData

    @if (Model.SideMenuItems.Count > 0)
    {
        <ul>
            @foreach (var subMenuItem in Model.SideMenuItems)
            {
                <li class="@subMenuItem.IsSelected ? 'selected' : @String.Empty ">
                    <a href="@subMenuItem.Url">
                        @if (!String.IsNullOrEmpty(subMenuItem.IconUrl))
                        {
                            <img src="@subMenuItem.IconUrl" alt="" />
                        }
                        @subMenuItem.Text
                    </a>
                </li>
            }
        </ul>
    }